# Generated by Django 6.0.3 on 2026-03-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_parution', models.DateField(verbose_name='Date de Parution')),
                ('isbn', models.CharField(max_length=20)),
                ('auteur', models.ManyToManyField(to='bibliotheque.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.categorie')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.edition')),
            ],
        ),
    ]
