# Generated by Django 6.0.3 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='livre',
            name='date_parution',
            field=models.PositiveIntegerField(verbose_name='Date de Parution'),
        ),
    ]
